language: node_js

services:
  - redis-server
  - postgresql

node_js:
  - 11

env:
  - REACT_APP_API_URL=http://localhost:8000 POSTGRES_HOST=postgres://postgres:postgres@localhost:5432/postgres GOOGLE_CLIENT_ID=CLIENT_ID GOOGLE_CLIENT_SECRET=CLIENT_SECRET REDIS_URL=redis://localhost:6379 API_URL=http://localhost:8000 ENABLE_DATABASE_SSL=0

addons:
  postgresql: "9.5"
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

before_script:
  - psql -c "ALTER USER postgres PASSWORD 'postgres';"

install:
  - cd api && npm install && cd ../
  - cd frontend && npm install
  - cd ../test && npm install

script:
  - cd ../test && npm start &
  - sleep 5 && cd ../frontend && npm start &
  - sleep 5 && npm test
  - cd ../test && npm test
