version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    restart: always
    environment:
      REACT_APP_API_URL: ${API_URL}
      POSTGRES_HOST: 'postgres://postgres:postgres@postgres:5432/postgres'
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      REDIS_URL: 'redis://cache:6379'
      API_URL: ${API_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      ENABLE_DATABASE_SSL: ${ENABLE_DATABASE_SSL:-0}

  scraper:
    image: scraper
    environment:
      REDIS_URL: 'redis://cache:6379'
      POSTGRES_HOST: 'postgres'
      API_URL: 'http://app:8000'
    depends_on:
      - redis

  redis:
    image: redis
    container_name: cache

volumes:
  postgres: ~
