version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  scraper:
    image: scraper
    build:
      context: .
      dockerfile: scraper/Dockerfile
    environment:
      REDIS_URL: 'redis://cache:6379'
      POSTGRES_HOST: 'postgres'
    depends_on:
      - redis

  redis:
    image: redis
    container_name: cache

  api:
    # restart: always
    build:
      context: .
      dockerfile: storage/Dockerfile
    environment:
      POSTGRES_HOST: 'postgres://postgres:postgres@postgres:5432/postgres'
    depends_on:
      - postgres
volumes:
  postgres: ~
