version: '3.4'

services:
  app:
    command: 'npm start'
    ports:
      - 8000:8000
    volumes:
      - ./node_modules:/usr/src/app/node_modules
      - ./frontend/node_modules:/usr/src/app/frontend/node_modules
      - ./api:/usr/src/app/api
  redis:
    ports:
      - 6379:6379
