version: '3.4'

services:
  monitor:
    image: scraper
    ports:
      - 4567:4567
    command: 'npm run monitor'
    depends_on:
      - scraper
      - postgres
      - redis

  app:
    command: 'npm start'
    ports:
      - 8000:8000

  redis:
    ports:
      - 6379:6379
